config/routes.rb
Myblog::Application.routes.draw do
  resources :gazos

  get "record/index"

  get "home/index"
  post "home/archive"
  get "home/find"
  post "home/find"
  get "entries/upload"
  post "entries/upload"
  get "gazos/index"
  
  resources :entries

  root to: 'home#index'

  match ':controller(/:action(/:id))', via: [ :get, :post, :patch ]

end

app/models/entry.rb
require 'hikidoc'

class Entry < ActiveRecord::Base
	def to_html
#		HikiDoc.to_html(body, :level =>3)
   HikiDoc.to_html(body)
	end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :auth, only: [:index, :new, :edit]

  # GET /entries
  # GET /entries.json
  def index
    # @entries = Entry.all
		@q = Entry.ransack(params[:q])
		@entries = @q.result.order(created_at: :desc)
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    counter = @entry.count
    if counter == nil then
      counter = 0
    end
    counter += 1
    @entry.count = counter
    @entry.save
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  def upload_process
    # アップロードファイルを取得
    file = params[:upfile]
    # ファイルのベース名（パスを除いた部分）を取得
    name = file.original_filename
    # 許可する拡張子を定義
    perms = ['.jpg', '.jpeg', '.gif', '.png']
    # 配列permsにアップロードファイルの拡張子に合致するものがあるか
    if !perms.include?(File.extname(name).downcase)
      @result = 'アップロードできるのは画像ファイルのみです。'
      # アップロードファイルのサイズが1MB以下であるか
    elsif file.size > 1.megabyte
      @result = 'ファイルサイズは1MBまでです。'
    else
      File.open("app/assets/images/upload/#{name}", 'wb') { |f| f.write(file.read) }
      @result = "/assets/upload/#{name}:アップロードしました。"
    end
    # 成功/エラーメッセージを保存
    render 'upload'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :body, :cathegory, :tag, :count, :created_at)
    end

    def auth
      # userID/Password
      name = 'billie'
      passwd = '0aebf3a9339a0d976e082525062cb64cfc9ba651'
      # 入力されたname,passwordを上のname,passwdと比較する
      authenticate_or_request_with_http_basic('nukblog') do |n,p|
        n == name &&
          Digest::SHA1.hexdigest(p) == passwd
      end
    end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
    <div class="field">
    <%= f.label :cathegory %><br>
    <%= f.text_field :cathegory %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count, size: 5 %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at, use_month_numbers: true %>
  </div>
  <div class="actions btn44aria">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<article>

	<h2>Editing Entry</h2>

	<%= render 'form' %>

	<p class="action">
		<%= link_to '', @entry, class: 'fa fa-picture-o fa-3x' %>
		<%= link_to '', entries_path, class: 'fa fa-wrench fa-3x' %>
	</p>

</article>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<article>

<h2>検索</h2>

<%= search_form_for @q do |f| %>
<%= f.label :title_cont, '題名' %>
<%= f.search_field :title_cont %><br />
<%= f.label :body_cont, '本文' %>
<%= f.search_field :body_cont %><br />
<%= f.label :cathegory_cont, 'カテゴリ' %>
<%= f.search_field :cathegory_cont %><br />
<%= f.label :tag_cont, 'タグ' %>
<%= f.search_field :tag_cont %>
<div> 
	<%= f.submit '検索する' %>
</div>
<% end %>

  <div class="swipe-list theme-swipe-list">
    <% @entries.each do |entry| %>
      <div class="list js-swipeList clearfix">
              <%# 画面本体部分 %>
        <div class="list-body js-swipeListTarget">
          <div class="list-contents list-cell <%= cycle('list-line-odd', 'list-line-even') %>">
    				<div class="title"><%= link_to h(entry.title), entry %></div>
            <div class="des1">
              <p class="cathegory"><%= entry.cathegory %></p>
              <p class="tag"><%= entry.tag %></p>
            </div>
            <div class="des2">
              <p class="count"><%= entry.count %></p>
    				  <p class="date">
                <%= entry.created_at.strftime("%Y") %>
                <%= entry.created_at.strftime("%m-%d") %>
                <%= entry.created_at.strftime("%H:%M") %>
              </p>
            </div><!-- .des2 -->
          </div><!-- .list-contents .list-cell -->
          <div class="list-arrow list-cell"><i class="fa fa-angle-double-left"></i></div>
        </div><!-- .list-body .js-swipeListTarget -->
            <%# 以下、右側リスト部分 %>
        <div class="list-btn js-swipeListBtn">
          <ul class="action clearfix">
            <li><%= link_to '', entry, class: 'fa fa-picture-o' %></li>
            <li><%= link_to '', edit_entry_path(entry), class: 'fa fa-edit' %></li>
            <li><%= link_to '', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-trash' %>
          </ul>
        </div><!-- .list-btn .js-swipeListBtn -->
      </div><!-- .list .js-swipeList .clearfix -->
    <% end %>
  </div><!-- .swipe-list .theme-swipe-list -->
<br>

<%= link_to 'New Entry', new_entry_path %>

</article>

app/views/entries/new.html.erb
<article>

	<h2>New Entry</h2>

	<%= render 'form' %>

	<p class="action">
		<%= link_to '', entries_path, class: 'fa fa-wrench fa-3x' %>
	</p>

</article>

app/views/entries/show.html.erb
<article>

<p id="notice"><%= notice %></p>

	<h2 class="home-title">
		<%= @entry.title %>
	</h2>

	<p>
	  <%== @entry.to_html %>
	</p>

	<p>
		<strong>カテゴリ:</strong>
		<%= @entry.cathegory %>
	</p>

	<p>
		<strong>タグ:</strong>
		<%= @entry.tag %>
	</p>

	<p>
		<% count = @entry.count.to_i + 0 %>
		<strong>Count:</strong>
		<%= @entry.count %>
	</p>

	<p>
	  <strong>DATE:</strong>
	  <%= @entry.created_at %>
	</p>

	<p class="action">
		<%= link_to '', edit_entry_path(@entry), class: 'fa fa-edit fa-3x' %>
		<%= link_to '', home_archive_path, class: 'fa fa-list fa-3x' %>
	</p>
</article>

app/views/entries/upload.html.erb
<article>
	<div class="upload_field">
		<%= form_tag({ action: :upload_process }, multipart: true) do %>
			<label>ファイルを指定:<%= file_field_tag :upfile, size: 50 %></label>
			<%= submit_tag 'アップロード' %>
		<% end %>
		<p>
			<%= @result %>
		</p>
	</div>
	<%= button_to '閉じる'  %>
</article>