config/routes.rb
Myblog::Application.routes.draw do
  resources :gazos

  get "record/index"

  get "home/index"
  post "home/archive"
  get "home/find"
  post "home/find"
  get "entries/upload"
  post "entries/upload"
  get "gazos/index"
  
  resources :entries

  root to: 'home#index'

  match ':controller(/:action(/:id))', via: [ :get, :post, :patch ]

end

app/models/gazo.rb
class Gazo < ActiveRecord::Base

	# アップロードファイルの妥当性をfile_invalid?メソッドで検証
	validate :file_invalid?

	# 書き込み専用のdataプロパティ(UploadFileオブジェクト)を定義
	def data=(data)
		self.ctype = data.content_type	# ctypeプロパティにコンテンツタイプをセット
		self.image = data.read					# imageプロパティにファイル本体をセット
	end

	# アップロードファイルの妥当性を検証するfile_invalid?メソッドを定義
	private
	def file_invalid?
		ps = ['image/jpeg', 'image/gif', 'image/png']
		errors.add(:image, 'は画像ファイルではありません。') if !ps.include?(self.ctype)
		errors.add(:image, 'のサイズが1MBを超えています。') if self.image.length > 1.megabyte
	end

end

app/controllers/gazos_controller.rb
class GazosController < ApplicationController
  before_action :set_gazo, only: [:show, :edit, :update, :destroy]
  before_action :auth, only: [:index, :new, :edit]

  # GET /gazos
  # GET /gazos.json
  def index
    @gazos = Gazo.all
  end

  # GET /gazos/1
  # GET /gazos/1.json
  def show
  end

  # GET /gazos/new
  def new
    @gazo = Gazo.new
  end

  # GET /gazos/1/edit
  def edit
  end

  # POST /gazos
  # POST /gazos.json
  def create
    @gazo = Gazo.new(gazo_params)

    respond_to do |format|
      if @gazo.save
        format.html { redirect_to @gazo, notice: 'Gazo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gazo }
      else
        format.html { render action: 'new' }
        format.json { render json: @gazo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gazos/1
  # PATCH/PUT /gazos/1.json
  def update
    respond_to do |format|
      if @gazo.update(gazo_params)
        format.html { redirect_to @gazo, notice: 'Gazo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gazo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gazos/1
  # DELETE /gazos/1.json
  def destroy
    @gazo.destroy
    respond_to do |format|
      format.html { redirect_to gazos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gazo
      @gazo = Gazo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gazo_params
      params.require(:gazo).permit(:file, :comment, :ctype, :image)
    end

    def auth
      # userID/Password
      name = 'billie'
      passwd = '0aebf3a9339a0d976e082525062cb64cfc9ba651'
      # 入力されたname,passwordを上のname,passwdと比較する
      authenticate_or_request_with_http_basic('nukblog') do |n,p|
        n == name &&
          Digest::SHA1.hexdigest(p) == passwd
      end
    end
end

app/helpers/gazos_helper.rb
module GazosHelper
end

app/views/gazos/_form.html.erb
<%= form_for(@gazo, url: {controller: :ctrl, action: :updb_process, id: @gazo},
  html:{multipart: true}) do |f| %>
  <% if @gazo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gazo.errors.count, "error") %> prohibited this gazo from being saved:</h2>

      <ul>
      <% @gazo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% id_no = @gazo.id %>
  <% if id_no == nil then %>
  <%  id_no = 1 %>
  <% end %>

  <%= "id : #{@gazo.id}" %>

  <div class="field">
    <%= f.label :file %><br>
    <%= f.text_field :file %>
    <%#= @gazo.file %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field image">
    <%= f.label :image %><br>
    <%= image_tag url_for(controller: :ctrl, action: :show_image, id: id_no), id: 'outputList' %>    
  </div>
  <div class="field btn44aria">
    <%= f.label :data, 'アップ画像' %><br>
    <%= f.file_field :data %>
    <div id="file_size"></div>
  </div>
  <div class="actions btn44aria">
    <%= f.submit 'アップロード' %>
  </div>
<% end %>

app/views/gazos/edit.html.erb
<article>

<h1>Editing gazo</h1>

<%= render 'form' %>

<p class="action">
	<%= link_to '', @gazo, class: 'fa fa-picture-o fa-3x' %>
	<%= link_to '', gazos_path, class: 'fa fa-list fa-3x' %>
</p>

</article>

app/views/gazos/index.html.erb
<article>

<h1>Listing gazos</h1>
<div class="list-header clearfix">
  <%= button_to 'New Gazo', new_gazo_path, class: 'new_gazo_button button44_submit'%>
  <%# p id="shoshiki" onclick=shoshiki()>書式</p %>
  <p id="shoshiki">書式</p>
</div>

<div class="swipe-list theme-swipe-list">
  <% @gazos.each do |gazo| %>
    <div class="list js-swipeList clearfix">
      <%# 画面本体部分 %>
      <div class="list-body js-swipeListTarget">
        <div class="list-contents list-cell <%= cycle('list-line-odd', 'list-line-even') %>">
          <dl class="clearfix">
            <dt class="fileInfo">
                <%= "id:#{gazo.id}" %> <%# gazo.file %><br>
              <%= gazo.comment %><br>
              <%#= gazo.ctype %></dt>
            <dd class="image"><%= link_to image_tag(url_for(controller: :ctrl, action: :show_image, id: gazo.id)), gazo %></dd>
          </dl>
        </div>
        <div class="list-arrow list-cell"><i class="fa fa-angle-double-left"></i></div>
      </div>
      <%# 以下、右側リスト部分 %>
      <div class="list-btn js-swipeListBtn">
        <ul class="action clearfix">
          <li><%= link_to '', gazo, class: 'fa fa-picture-o' %></li>
          <li><%= link_to '', edit_gazo_path(gazo), class: 'fa fa-edit' %></li>
          <li><%= link_to '', gazo, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-trash' %></li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

</article>

app/views/gazos/new.html.erb
<article>

<h1>New gazo</h1>

<%= render 'form' %>

<p class="action">
	<%= link_to '', gazos_path, class: 'fa fa-list fa-3x' %>
</p>

</article>

app/views/gazos/show.html.erb
<article>

<p id="notice"><%= notice %></p>

<p>
  <%= "id : #{@gazo.id}" %>
<p>
  <strong>File:</strong>
  <%= @gazo.file %>
  <%#= "ctrl/show_image/#{@gazo.id}" %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @gazo.comment %>
</p>

<p>
  <strong>Ctype:</strong>
  <%= @gazo.ctype %>
</p>

<p class="image">
  <%= image_tag(url_for(controller: :ctrl, action: :show_image, id: @gazo.id)) %>
</p>

<p class="action">
	<%= link_to '', edit_gazo_path(@gazo), class: 'fa fa-edit fa-3x' %>
	<%= link_to '', gazos_path, class: 'fa fa-list fa-3x' %>
<p>
	
</article>